# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := pnacl_support_extension
### Rules for action "generate_pnacl_support_extension":
quiet_cmd__home_padolph_chromium_src_ppapi_native_client_src_untrusted_pnacl_support_extension_pnacl_support_extension_gyp_pnacl_support_extension_target_generate_pnacl_support_extension = ACTION _home_padolph_chromium_src_ppapi_native_client_src_untrusted_pnacl_support_extension_pnacl_support_extension_gyp_pnacl_support_extension_target_generate_pnacl_support_extension $@
cmd__home_padolph_chromium_src_ppapi_native_client_src_untrusted_pnacl_support_extension_pnacl_support_extension_gyp_pnacl_support_extension_target_generate_pnacl_support_extension = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ppapi/native_client/src/untrusted/pnacl_support_extension; mkdir -p $(builddir)/pnacl; python pnacl_component_crx_gen.py "--dest=$(builddir)/pnacl" "--lib_override=x64,$(obj)/gen/tc_pnacl_translate/lib-x86-64/libpnacl_irt_shim.a" "--installer_only=x64" 0.0.0.1

$(builddir)/pnacl/pnacl_public_pnacl_json: obj := $(abs_obj)
$(builddir)/pnacl/pnacl_public_pnacl_json: builddir := $(abs_builddir)
$(builddir)/pnacl/pnacl_public_pnacl_json: TOOLSET := $(TOOLSET)
$(builddir)/pnacl/pnacl_public_pnacl_json: ppapi/native_client/src/untrusted/pnacl_support_extension/pnacl_component_crx_gen.py $(obj)/gen/tc_pnacl_translate/lib-x86-64/libpnacl_irt_shim.a FORCE_DO_CMD
	$(call do_cmd,_home_padolph_chromium_src_ppapi_native_client_src_untrusted_pnacl_support_extension_pnacl_support_extension_gyp_pnacl_support_extension_target_generate_pnacl_support_extension)
$(builddir)/pnacl/pnacl_public_x86_64_crtbegin_o $(builddir)/pnacl/pnacl_public_x86_64_crtbeginS_o $(builddir)/pnacl/pnacl_public_x86_64_ld_nexe $(builddir)/pnacl/pnacl_public_x86_64_libcrt_platform_a $(builddir)/pnacl/pnacl_public_x86_64_libgcc_a $(builddir)/pnacl/pnacl_public_x86_64_libgcc_eh_a $(builddir)/pnacl/pnacl_public_x86_64_libpnacl_irt_shim_a $(builddir)/pnacl/pnacl_public_x86_64_llc_nexe: $(builddir)/pnacl/pnacl_public_pnacl_json
$(builddir)/pnacl/pnacl_public_x86_64_crtbegin_o $(builddir)/pnacl/pnacl_public_x86_64_crtbeginS_o $(builddir)/pnacl/pnacl_public_x86_64_ld_nexe $(builddir)/pnacl/pnacl_public_x86_64_libcrt_platform_a $(builddir)/pnacl/pnacl_public_x86_64_libgcc_a $(builddir)/pnacl/pnacl_public_x86_64_libgcc_eh_a $(builddir)/pnacl/pnacl_public_x86_64_libpnacl_irt_shim_a $(builddir)/pnacl/pnacl_public_x86_64_llc_nexe: ;

all_deps += $(builddir)/pnacl/pnacl_public_pnacl_json $(builddir)/pnacl/pnacl_public_x86_64_crtbegin_o $(builddir)/pnacl/pnacl_public_x86_64_crtbeginS_o $(builddir)/pnacl/pnacl_public_x86_64_ld_nexe $(builddir)/pnacl/pnacl_public_x86_64_libcrt_platform_a $(builddir)/pnacl/pnacl_public_x86_64_libgcc_a $(builddir)/pnacl/pnacl_public_x86_64_libgcc_eh_a $(builddir)/pnacl/pnacl_public_x86_64_libpnacl_irt_shim_a $(builddir)/pnacl/pnacl_public_x86_64_llc_nexe
action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_pnacl_support_extension_pnacl_support_extension_gyp_pnacl_support_extension_target_generate_pnacl_support_extension_outputs := $(builddir)/pnacl/pnacl_public_pnacl_json $(builddir)/pnacl/pnacl_public_x86_64_crtbegin_o $(builddir)/pnacl/pnacl_public_x86_64_crtbeginS_o $(builddir)/pnacl/pnacl_public_x86_64_ld_nexe $(builddir)/pnacl/pnacl_public_x86_64_libcrt_platform_a $(builddir)/pnacl/pnacl_public_x86_64_libgcc_a $(builddir)/pnacl/pnacl_public_x86_64_libgcc_eh_a $(builddir)/pnacl/pnacl_public_x86_64_libpnacl_irt_shim_a $(builddir)/pnacl/pnacl_public_x86_64_llc_nexe


DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-format \
	-Wno-unused-result \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated

INCS_Debug :=

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-format \
	-Wno-unused-result \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated

INCS_Release :=

OBJS :=

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/ppapi/native_client/src/untrusted/pnacl_irt_shim/pnacl_irt_shim.stamp $(obj).target/native_client/prep_toolchain.stamp

# Make sure our actions/rules run before any of us.
$(OBJS): | $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_pnacl_support_extension_pnacl_support_extension_gyp_pnacl_support_extension_target_generate_pnacl_support_extension_outputs)


### Rules for final target.
# Build our special outputs first.
$(obj).target/ppapi/native_client/src/untrusted/pnacl_support_extension/pnacl_support_extension.stamp: | $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_pnacl_support_extension_pnacl_support_extension_gyp_pnacl_support_extension_target_generate_pnacl_support_extension_outputs)

# Preserve order dependency of special output on deps.
$(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_pnacl_support_extension_pnacl_support_extension_gyp_pnacl_support_extension_target_generate_pnacl_support_extension_outputs): | $(obj).target/ppapi/native_client/src/untrusted/pnacl_irt_shim/pnacl_irt_shim.stamp $(obj).target/native_client/prep_toolchain.stamp

$(obj).target/ppapi/native_client/src/untrusted/pnacl_support_extension/pnacl_support_extension.stamp: TOOLSET := $(TOOLSET)
$(obj).target/ppapi/native_client/src/untrusted/pnacl_support_extension/pnacl_support_extension.stamp: $(obj).target/ppapi/native_client/src/untrusted/pnacl_irt_shim/pnacl_irt_shim.stamp $(obj).target/native_client/prep_toolchain.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/ppapi/native_client/src/untrusted/pnacl_support_extension/pnacl_support_extension.stamp
# Add target alias
.PHONY: pnacl_support_extension
pnacl_support_extension: $(obj).target/ppapi/native_client/src/untrusted/pnacl_support_extension/pnacl_support_extension.stamp

# Add target alias to "all" target.
.PHONY: all
all: pnacl_support_extension

