# This file is generated by gyp; do not edit.

export builddir_name ?= /home/padolph/chromium/src/ppapi/native_client/src/trusted/plugin/out
.PHONY: all
all:
	$(MAKE) -C ../../../../.. ppGoogleNaClPluginChrome
