# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := ppapi_stub_lib
### Rules for action "build newlib x86-64 nlib":
quiet_cmd__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_64_nlib = ACTION _home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_64_nlib $@
cmd__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_64_nlib = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ppapi/native_client/src/untrusted/irt_stub; mkdir -p $(obj)/gen/tc_newlib/lib64; python ../../../../../native_client/build/build_nexe.py -t "$(obj)/gen/sdk/toolchain/" --arch x86-64 --build newlib_nlib --root ../../../../.. --name "$(obj)/gen/tc_newlib/lib64/libppapi_stub.a" --objdir "$(obj).$(TOOLSET)/ppapi_stub_lib/geni/newlib-x86-64/ppapi_stub_lib" "--include-dirs=$(obj)/gen/tc_newlib/include ../../../../.. ../../../../../ppapi ../../../.." "--lib-dirs= " "--compile_flags=-m64 -mtls-use-call -fomit-frame-pointer -fasynchronous-unwind-tables  -O2 -g -Wall -Werror -fdiagnostics-show-option " "--defines=__linux__ \"__STDC_LIMIT_MACROS=1\" \"__STDC_FORMAT_MACROS=1\" \"_GNU_SOURCE=1\" \"_BSD_SOURCE=1\" \"_POSIX_C_SOURCE=199506\" \"_XOPEN_SOURCE=600\" \"DYNAMIC_ANNOTATIONS_ENABLED=1\" \"DYNAMIC_ANNOTATIONS_PREFIX=NACL_\" \"NACL_BUILD_ARCH=x86\" \"_FILE_OFFSET_BITS=64\" CHROMIUM_BUILD \"USE_DEFAULT_RENDER_THEME=1\" \"USE_LIBJPEG_TURBO=1\" \"USE_NSS=1\" ENABLE_ONE_CLICK_SIGNIN \"GTK_DISABLE_SINGLE_INCLUDES=1\" \"ENABLE_REMOTING=1\" \"ENABLE_WEBRTC=1\" ENABLE_PEPPER_THREADING ENABLE_CONFIGURATION_POLICY ENABLE_INPUT_SPEECH ENABLE_NOTIFICATIONS \"ENABLE_GPU=1\" \"ENABLE_EGLIMAGE=1\" \"USE_SKIA=1\" \"ENABLE_TASK_MANAGER=1\" \"ENABLE_WEB_INTENTS=1\" \"ENABLE_EXTENSIONS=1\" \"ENABLE_PLUGIN_INSTALLATION=1\" \"ENABLE_PLUGINS=1\" \"ENABLE_SESSION_SERVICE=1\" \"ENABLE_THEMES=1\" \"ENABLE_BACKGROUND=1\" \"ENABLE_AUTOMATION=1\" \"ENABLE_GOOGLE_NOW=1\" \"ENABLE_LANGUAGE_DETECTION=1\" \"ENABLE_PRINTING=1\" \"ENABLE_CAPTIVE_PORTAL_DETECTION=1\"" "--link_flags=-B$(obj)/gen/tc_newlib/lib64  " "--source-list=newlib-x86-64.ppapi_stub_lib.source_list.gypcmd"

$(obj)/gen/tc_newlib/lib64/libppapi_stub.a: obj := $(abs_obj)
$(obj)/gen/tc_newlib/lib64/libppapi_stub.a: builddir := $(abs_builddir)
$(obj)/gen/tc_newlib/lib64/libppapi_stub.a: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_newlib/lib64/libppapi_stub.a: native_client/build/build_nexe.py native_client/src/include/elf32.h native_client/src/include/elf_auxv.h native_client/src/include/elf_constants.h native_client/src/include/nacl_base.h native_client/src/include/nacl_compiler_annotations.h native_client/src/include/nacl_macros.h native_client/src/include/portability.h native_client/src/include/win/port_win.h native_client/src/third_party/valgrind/memcheck.h native_client/src/trusted/service_runtime/include/bits/wordsize.h native_client/src/untrusted/irt/irt.h native_client/src/untrusted/irt/irt_ppapi.h ppapi/c/pp_macros.h ppapi/c/pp_module.h ppapi/c/pp_stdint.h ppapi/c/ppb.h ppapi/c/ppp.h ppapi/native_client/src/untrusted/irt_stub/plugin_main_irt.c ppapi/native_client/src/untrusted/irt_stub/ppapi_plugin_main.c ppapi/native_client/src/untrusted/irt_stub/ppapi_plugin_start.c ppapi/native_client/src/untrusted/irt_stub/thread_creator.c ppapi/native_client/src/untrusted/irt_stub/newlib-x86-64.ppapi_stub_lib.source_list.gypcmd $(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.prep FORCE_DO_CMD
	$(call do_cmd,_home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_64_nlib)

all_deps += $(obj)/gen/tc_newlib/lib64/libppapi_stub.a
action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_64_nlib_outputs := $(obj)/gen/tc_newlib/lib64/libppapi_stub.a

### Rules for action "build newlib x86-32 nlib":
quiet_cmd__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_32_nlib = ACTION _home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_32_nlib $@
cmd__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_32_nlib = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ppapi/native_client/src/untrusted/irt_stub; mkdir -p $(obj)/gen/tc_newlib/lib32; python ../../../../../native_client/build/build_nexe.py -t "$(obj)/gen/sdk/toolchain/" --arch x86-32 --build newlib_nlib --root ../../../../.. --name "$(obj)/gen/tc_newlib/lib32/libppapi_stub.a" --objdir "$(obj).$(TOOLSET)/ppapi_stub_lib/geni/newlib-x86-32/ppapi_stub_lib" "--include-dirs=$(obj)/gen/tc_newlib/include ../../../../.. ../../../../../ppapi ../../../.." "--lib-dirs=" "--compile_flags=-m32 -mtls-use-call -fomit-frame-pointer -fasynchronous-unwind-tables  -O2 -g -Wall -Werror -fdiagnostics-show-option " "--defines=__linux__ \"__STDC_LIMIT_MACROS=1\" \"__STDC_FORMAT_MACROS=1\" \"_GNU_SOURCE=1\" \"_BSD_SOURCE=1\" \"_POSIX_C_SOURCE=199506\" \"_XOPEN_SOURCE=600\" \"DYNAMIC_ANNOTATIONS_ENABLED=1\" \"DYNAMIC_ANNOTATIONS_PREFIX=NACL_\" \"NACL_BUILD_ARCH=x86\" \"_FILE_OFFSET_BITS=64\" CHROMIUM_BUILD \"USE_DEFAULT_RENDER_THEME=1\" \"USE_LIBJPEG_TURBO=1\" \"USE_NSS=1\" ENABLE_ONE_CLICK_SIGNIN \"GTK_DISABLE_SINGLE_INCLUDES=1\" \"ENABLE_REMOTING=1\" \"ENABLE_WEBRTC=1\" ENABLE_PEPPER_THREADING ENABLE_CONFIGURATION_POLICY ENABLE_INPUT_SPEECH ENABLE_NOTIFICATIONS \"ENABLE_GPU=1\" \"ENABLE_EGLIMAGE=1\" \"USE_SKIA=1\" \"ENABLE_TASK_MANAGER=1\" \"ENABLE_WEB_INTENTS=1\" \"ENABLE_EXTENSIONS=1\" \"ENABLE_PLUGIN_INSTALLATION=1\" \"ENABLE_PLUGINS=1\" \"ENABLE_SESSION_SERVICE=1\" \"ENABLE_THEMES=1\" \"ENABLE_BACKGROUND=1\" \"ENABLE_AUTOMATION=1\" \"ENABLE_GOOGLE_NOW=1\" \"ENABLE_LANGUAGE_DETECTION=1\" \"ENABLE_PRINTING=1\" \"ENABLE_CAPTIVE_PORTAL_DETECTION=1\"" "--link_flags=-m32 -B$(obj)/gen/tc_newlib/lib32  " "--source-list=newlib-x86-32.ppapi_stub_lib.source_list.gypcmd"

$(obj)/gen/tc_newlib/lib32/libppapi_stub.a: obj := $(abs_obj)
$(obj)/gen/tc_newlib/lib32/libppapi_stub.a: builddir := $(abs_builddir)
$(obj)/gen/tc_newlib/lib32/libppapi_stub.a: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_newlib/lib32/libppapi_stub.a: native_client/build/build_nexe.py native_client/src/include/elf32.h native_client/src/include/elf_auxv.h native_client/src/include/elf_constants.h native_client/src/include/nacl_base.h native_client/src/include/nacl_compiler_annotations.h native_client/src/include/nacl_macros.h native_client/src/include/portability.h native_client/src/include/win/port_win.h native_client/src/third_party/valgrind/memcheck.h native_client/src/trusted/service_runtime/include/bits/wordsize.h native_client/src/untrusted/irt/irt.h native_client/src/untrusted/irt/irt_ppapi.h ppapi/c/pp_macros.h ppapi/c/pp_module.h ppapi/c/pp_stdint.h ppapi/c/ppb.h ppapi/c/ppp.h ppapi/native_client/src/untrusted/irt_stub/plugin_main_irt.c ppapi/native_client/src/untrusted/irt_stub/ppapi_plugin_main.c ppapi/native_client/src/untrusted/irt_stub/ppapi_plugin_start.c ppapi/native_client/src/untrusted/irt_stub/thread_creator.c ppapi/native_client/src/untrusted/irt_stub/newlib-x86-32.ppapi_stub_lib.source_list.gypcmd $(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.prep FORCE_DO_CMD
	$(call do_cmd,_home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_32_nlib)

all_deps += $(obj)/gen/tc_newlib/lib32/libppapi_stub.a
action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_32_nlib_outputs := $(obj)/gen/tc_newlib/lib32/libppapi_stub.a

### Rules for action "build glibc x86-64 nlib":
quiet_cmd__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_64_nlib = ACTION _home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_64_nlib $@
cmd__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_64_nlib = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ppapi/native_client/src/untrusted/irt_stub; mkdir -p $(obj)/gen/tc_glibc/lib64; python ../../../../../native_client/build/build_nexe.py -t "$(obj)/gen/sdk/toolchain/" --arch x86-64 --build glibc_nlib --root ../../../../.. --name "$(obj)/gen/tc_glibc/lib64/libppapi_stub.a" --objdir "$(obj).$(TOOLSET)/ppapi_stub_lib/geni/glibc-x86-64/ppapi_stub_lib" "--include-dirs=$(obj)/gen/tc_glibc/include ../../../../.. ../../../../../ppapi ../../../.." "--lib-dirs= " "--compile_flags=-m64 -fomit-frame-pointer -fasynchronous-unwind-tables  -O2 -g -Wall -Werror -fdiagnostics-show-option " "--defines=__linux__ \"__STDC_LIMIT_MACROS=1\" \"__STDC_FORMAT_MACROS=1\" \"_GNU_SOURCE=1\" \"_BSD_SOURCE=1\" \"_POSIX_C_SOURCE=199506\" \"_XOPEN_SOURCE=600\" \"DYNAMIC_ANNOTATIONS_ENABLED=1\" \"DYNAMIC_ANNOTATIONS_PREFIX=NACL_\" \"NACL_BUILD_ARCH=x86\" \"_FILE_OFFSET_BITS=64\" CHROMIUM_BUILD \"USE_DEFAULT_RENDER_THEME=1\" \"USE_LIBJPEG_TURBO=1\" \"USE_NSS=1\" ENABLE_ONE_CLICK_SIGNIN \"GTK_DISABLE_SINGLE_INCLUDES=1\" \"ENABLE_REMOTING=1\" \"ENABLE_WEBRTC=1\" ENABLE_PEPPER_THREADING ENABLE_CONFIGURATION_POLICY ENABLE_INPUT_SPEECH ENABLE_NOTIFICATIONS \"ENABLE_GPU=1\" \"ENABLE_EGLIMAGE=1\" \"USE_SKIA=1\" \"ENABLE_TASK_MANAGER=1\" \"ENABLE_WEB_INTENTS=1\" \"ENABLE_EXTENSIONS=1\" \"ENABLE_PLUGIN_INSTALLATION=1\" \"ENABLE_PLUGINS=1\" \"ENABLE_SESSION_SERVICE=1\" \"ENABLE_THEMES=1\" \"ENABLE_BACKGROUND=1\" \"ENABLE_AUTOMATION=1\" \"ENABLE_GOOGLE_NOW=1\" \"ENABLE_LANGUAGE_DETECTION=1\" \"ENABLE_PRINTING=1\" \"ENABLE_CAPTIVE_PORTAL_DETECTION=1\"" "--link_flags=-B$(obj)/gen/tc_glibc/lib64  " "--source-list=glibc-x86-64.ppapi_stub_lib.source_list.gypcmd"

$(obj)/gen/tc_glibc/lib64/libppapi_stub.a: obj := $(abs_obj)
$(obj)/gen/tc_glibc/lib64/libppapi_stub.a: builddir := $(abs_builddir)
$(obj)/gen/tc_glibc/lib64/libppapi_stub.a: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_glibc/lib64/libppapi_stub.a: native_client/build/build_nexe.py native_client/src/include/elf32.h native_client/src/include/elf_auxv.h native_client/src/include/elf_constants.h native_client/src/include/nacl_base.h native_client/src/include/nacl_compiler_annotations.h native_client/src/include/nacl_macros.h native_client/src/include/portability.h native_client/src/include/win/port_win.h native_client/src/third_party/valgrind/memcheck.h native_client/src/trusted/service_runtime/include/bits/wordsize.h native_client/src/untrusted/irt/irt.h native_client/src/untrusted/irt/irt_ppapi.h ppapi/c/pp_macros.h ppapi/c/pp_module.h ppapi/c/pp_stdint.h ppapi/c/ppb.h ppapi/c/ppp.h ppapi/native_client/src/untrusted/irt_stub/plugin_main_irt.c ppapi/native_client/src/untrusted/irt_stub/ppapi_plugin_main.c ppapi/native_client/src/untrusted/irt_stub/ppapi_plugin_start.c ppapi/native_client/src/untrusted/irt_stub/thread_creator.c ppapi/native_client/src/untrusted/irt_stub/glibc-x86-64.ppapi_stub_lib.source_list.gypcmd $(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.prep FORCE_DO_CMD
	$(call do_cmd,_home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_64_nlib)

all_deps += $(obj)/gen/tc_glibc/lib64/libppapi_stub.a
action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_64_nlib_outputs := $(obj)/gen/tc_glibc/lib64/libppapi_stub.a

### Rules for action "build glibc x86-32 nlib":
quiet_cmd__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_32_nlib = ACTION _home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_32_nlib $@
cmd__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_32_nlib = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ppapi/native_client/src/untrusted/irt_stub; mkdir -p $(obj)/gen/tc_glibc/lib32; python ../../../../../native_client/build/build_nexe.py -t "$(obj)/gen/sdk/toolchain/" --arch x86-32 --build glibc_nlib --root ../../../../.. --name "$(obj)/gen/tc_glibc/lib32/libppapi_stub.a" --objdir "$(obj).$(TOOLSET)/ppapi_stub_lib/geni/glibc-x86-32/ppapi_stub_lib" "--include-dirs=$(obj)/gen/tc_glibc/include ../../../../.. ../../../../../ppapi ../../../.." "--lib-dirs=" "--compile_flags=-m32 -fomit-frame-pointer -fasynchronous-unwind-tables  -O2 -g -Wall -Werror -fdiagnostics-show-option " "--defines=__linux__ \"__STDC_LIMIT_MACROS=1\" \"__STDC_FORMAT_MACROS=1\" \"_GNU_SOURCE=1\" \"_BSD_SOURCE=1\" \"_POSIX_C_SOURCE=199506\" \"_XOPEN_SOURCE=600\" \"DYNAMIC_ANNOTATIONS_ENABLED=1\" \"DYNAMIC_ANNOTATIONS_PREFIX=NACL_\" \"NACL_BUILD_ARCH=x86\" \"_FILE_OFFSET_BITS=64\" CHROMIUM_BUILD \"USE_DEFAULT_RENDER_THEME=1\" \"USE_LIBJPEG_TURBO=1\" \"USE_NSS=1\" ENABLE_ONE_CLICK_SIGNIN \"GTK_DISABLE_SINGLE_INCLUDES=1\" \"ENABLE_REMOTING=1\" \"ENABLE_WEBRTC=1\" ENABLE_PEPPER_THREADING ENABLE_CONFIGURATION_POLICY ENABLE_INPUT_SPEECH ENABLE_NOTIFICATIONS \"ENABLE_GPU=1\" \"ENABLE_EGLIMAGE=1\" \"USE_SKIA=1\" \"ENABLE_TASK_MANAGER=1\" \"ENABLE_WEB_INTENTS=1\" \"ENABLE_EXTENSIONS=1\" \"ENABLE_PLUGIN_INSTALLATION=1\" \"ENABLE_PLUGINS=1\" \"ENABLE_SESSION_SERVICE=1\" \"ENABLE_THEMES=1\" \"ENABLE_BACKGROUND=1\" \"ENABLE_AUTOMATION=1\" \"ENABLE_GOOGLE_NOW=1\" \"ENABLE_LANGUAGE_DETECTION=1\" \"ENABLE_PRINTING=1\" \"ENABLE_CAPTIVE_PORTAL_DETECTION=1\"" "--link_flags=-m32 -B$(obj)/gen/tc_glibc/lib32  " "--source-list=glibc-x86-32.ppapi_stub_lib.source_list.gypcmd"

$(obj)/gen/tc_glibc/lib32/libppapi_stub.a: obj := $(abs_obj)
$(obj)/gen/tc_glibc/lib32/libppapi_stub.a: builddir := $(abs_builddir)
$(obj)/gen/tc_glibc/lib32/libppapi_stub.a: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_glibc/lib32/libppapi_stub.a: native_client/build/build_nexe.py native_client/src/include/elf32.h native_client/src/include/elf_auxv.h native_client/src/include/elf_constants.h native_client/src/include/nacl_base.h native_client/src/include/nacl_compiler_annotations.h native_client/src/include/nacl_macros.h native_client/src/include/portability.h native_client/src/include/win/port_win.h native_client/src/third_party/valgrind/memcheck.h native_client/src/trusted/service_runtime/include/bits/wordsize.h native_client/src/untrusted/irt/irt.h native_client/src/untrusted/irt/irt_ppapi.h ppapi/c/pp_macros.h ppapi/c/pp_module.h ppapi/c/pp_stdint.h ppapi/c/ppb.h ppapi/c/ppp.h ppapi/native_client/src/untrusted/irt_stub/plugin_main_irt.c ppapi/native_client/src/untrusted/irt_stub/ppapi_plugin_main.c ppapi/native_client/src/untrusted/irt_stub/ppapi_plugin_start.c ppapi/native_client/src/untrusted/irt_stub/thread_creator.c ppapi/native_client/src/untrusted/irt_stub/glibc-x86-32.ppapi_stub_lib.source_list.gypcmd $(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.prep FORCE_DO_CMD
	$(call do_cmd,_home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_32_nlib)

all_deps += $(obj)/gen/tc_glibc/lib32/libppapi_stub.a
action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_32_nlib_outputs := $(obj)/gen/tc_glibc/lib32/libppapi_stub.a


DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-format \
	-Wno-unused-result \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated

INCS_Debug := \
	-Ippapi

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-format \
	-Wno-unused-result \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated

INCS_Release := \
	-Ippapi

OBJS := \
	$(obj).target/$(TARGET)/ppapi/native_client/src/untrusted/irt_stub/ppapi_plugin_main.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/untrusted/irt_stub/ppapi_plugin_start.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/untrusted/irt_stub/plugin_main_irt.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/untrusted/irt_stub/thread_creator.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/native_client/prep_toolchain.stamp

# Make sure our actions/rules run before any of us.
$(OBJS): | $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_64_nlib_outputs) $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_32_nlib_outputs) $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_64_nlib_outputs) $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_32_nlib_outputs)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
# Build our special outputs first.
$(obj).target/ppapi/native_client/src/untrusted/irt_stub/ppapi_stub_lib.stamp: | $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_64_nlib_outputs) $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_32_nlib_outputs) $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_64_nlib_outputs) $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_32_nlib_outputs)

# Preserve order dependency of special output on deps.
$(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_64_nlib_outputs) $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_newlib_x86_32_nlib_outputs) $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_64_nlib_outputs) $(action__home_padolph_chromium_src_ppapi_native_client_src_untrusted_irt_stub_irt_stub_gyp_ppapi_stub_lib_target_build_glibc_x86_32_nlib_outputs): | $(obj).target/native_client/prep_toolchain.stamp

$(obj).target/ppapi/native_client/src/untrusted/irt_stub/ppapi_stub_lib.stamp: TOOLSET := $(TOOLSET)
$(obj).target/ppapi/native_client/src/untrusted/irt_stub/ppapi_stub_lib.stamp: $(obj).target/native_client/prep_toolchain.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/ppapi/native_client/src/untrusted/irt_stub/ppapi_stub_lib.stamp
# Add target alias
.PHONY: ppapi_stub_lib
ppapi_stub_lib: $(obj).target/ppapi/native_client/src/untrusted/irt_stub/ppapi_stub_lib.stamp

# Add target alias to "all" target.
.PHONY: all
all: ppapi_stub_lib

