# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := ppapi_lib
### Generated for copy rule.
$(obj)/gen/tc_newlib/include/nacl/call_on_main_thread.h: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_newlib/include/nacl/call_on_main_thread.h: ppapi/native_client/src/trusted/weak_ref/call_on_main_thread.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_newlib/include/nacl/call_on_main_thread.h
$(obj)/gen/tc_newlib/include/nacl/ppruntime.h: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_newlib/include/nacl/ppruntime.h: ppapi/native_client/src/shared/ppapi_proxy/ppruntime.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_newlib/include/nacl/ppruntime.h
$(obj)/gen/tc_glibc/include/nacl/call_on_main_thread.h: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_glibc/include/nacl/call_on_main_thread.h: ppapi/native_client/src/trusted/weak_ref/call_on_main_thread.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_glibc/include/nacl/call_on_main_thread.h
$(obj)/gen/tc_glibc/include/nacl/ppruntime.h: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_glibc/include/nacl/ppruntime.h: ppapi/native_client/src/shared/ppapi_proxy/ppruntime.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_glibc/include/nacl/ppruntime.h
$(obj)/gen/tc_newlib/lib32/libppapi.a: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_newlib/lib32/libppapi.a: ppapi/native_client/src/untrusted/irt_stub/libppapi.a FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_newlib/lib32/libppapi.a
$(obj)/gen/tc_newlib/lib64/libppapi.a: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_newlib/lib64/libppapi.a: ppapi/native_client/src/untrusted/irt_stub/libppapi.a FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_newlib/lib64/libppapi.a
$(obj)/gen/tc_glibc/lib32/libppapi.a: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_glibc/lib32/libppapi.a: ppapi/native_client/src/untrusted/irt_stub/libppapi.a FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_glibc/lib32/libppapi.a
$(obj)/gen/tc_glibc/lib32/libppapi.so: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_glibc/lib32/libppapi.so: ppapi/native_client/src/untrusted/irt_stub/libppapi.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_glibc/lib32/libppapi.so
$(obj)/gen/tc_glibc/lib64/libppapi.a: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_glibc/lib64/libppapi.a: ppapi/native_client/src/untrusted/irt_stub/libppapi.a FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_glibc/lib64/libppapi.a
$(obj)/gen/tc_glibc/lib64/libppapi.so: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_glibc/lib64/libppapi.so: ppapi/native_client/src/untrusted/irt_stub/libppapi.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_glibc/lib64/libppapi.so
$(obj)/gen/tc_newlib/libarm/libppapi.a: TOOLSET := $(TOOLSET)
$(obj)/gen/tc_newlib/libarm/libppapi.a: ppapi/native_client/src/untrusted/irt_stub/libppapi.a FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(obj)/gen/tc_newlib/libarm/libppapi.a
_home_padolph_chromium_src_ppapi_native_client_native_client_gyp_ppapi_lib_target_copies = $(obj)/gen/tc_newlib/include/nacl/call_on_main_thread.h $(obj)/gen/tc_newlib/include/nacl/ppruntime.h $(obj)/gen/tc_glibc/include/nacl/call_on_main_thread.h $(obj)/gen/tc_glibc/include/nacl/ppruntime.h $(obj)/gen/tc_newlib/lib32/libppapi.a $(obj)/gen/tc_newlib/lib64/libppapi.a $(obj)/gen/tc_glibc/lib32/libppapi.a $(obj)/gen/tc_glibc/lib32/libppapi.so $(obj)/gen/tc_glibc/lib64/libppapi.a $(obj)/gen/tc_glibc/lib64/libppapi.so $(obj)/gen/tc_newlib/libarm/libppapi.a

### Rules for final target.
# Build our special outputs first.
$(obj).target/ppapi/native_client/ppapi_lib.stamp: | $(_home_padolph_chromium_src_ppapi_native_client_native_client_gyp_ppapi_lib_target_copies)

# Preserve order dependency of special output on deps.
$(_home_padolph_chromium_src_ppapi_native_client_native_client_gyp_ppapi_lib_target_copies): | $(obj).target/native_client/src/untrusted/pthread/pthread_lib.stamp $(obj).target/ppapi/native_client/src/untrusted/irt_stub/ppapi_stub_lib.stamp

$(obj).target/ppapi/native_client/ppapi_lib.stamp: TOOLSET := $(TOOLSET)
$(obj).target/ppapi/native_client/ppapi_lib.stamp: $(obj).target/native_client/src/untrusted/pthread/pthread_lib.stamp $(obj).target/ppapi/native_client/src/untrusted/irt_stub/ppapi_stub_lib.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/ppapi/native_client/ppapi_lib.stamp
# Add target alias
.PHONY: ppapi_lib
ppapi_lib: $(obj).target/ppapi/native_client/ppapi_lib.stamp

# Add target alias to "all" target.
.PHONY: all
all: ppapi_lib

