# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := nacl_ppapi_browser
DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNACL_LINUX=1' \
	'-DNACL_ANDROID=0' \
	'-DNACL_OSX=0' \
	'-DNACL_WINDOWS=0' \
	'-D_BSD_SOURCE=1' \
	'-D_POSIX_C_SOURCE=199506' \
	'-D_XOPEN_SOURCE=600' \
	'-D_GNU_SOURCE=1' \
	'-D__STDC_LIMIT_MACROS=1' \
	'-D__STDC_FORMAT_MACROS' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DNACL_TARGET_SUBARCH=64' \
	'-DNACL_TARGET_ARCH=x86' \
	'-DNACL_BUILD_SUBARCH=64' \
	'-DNACL_BUILD_ARCH=x86' \
	'-D__STDC_CONSTANT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-m64 \
	-fno-exceptions \
	-Wall \
	-O0 \
	-g \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-fno-rtti \
	-fno-threadsafe-statics

INCS_Debug := \
	-Inative_client/src/third_party \
	-I. \
	-Ippapi/native_client/src/shared/ppapi_proxy/trusted \
	-Ippapi

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNACL_LINUX=1' \
	'-DNACL_ANDROID=0' \
	'-DNACL_OSX=0' \
	'-DNACL_WINDOWS=0' \
	'-D_BSD_SOURCE=1' \
	'-D_POSIX_C_SOURCE=199506' \
	'-D_XOPEN_SOURCE=600' \
	'-D_GNU_SOURCE=1' \
	'-D__STDC_LIMIT_MACROS=1' \
	'-D__STDC_FORMAT_MACROS' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DNACL_TARGET_SUBARCH=64' \
	'-DNACL_TARGET_ARCH=x86' \
	'-DNACL_BUILD_SUBARCH=64' \
	'-DNACL_BUILD_ARCH=x86' \
	'-D__STDC_CONSTANT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-m64 \
	-fno-exceptions \
	-Wall \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-fno-rtti \
	-fno-threadsafe-statics

INCS_Release := \
	-Inative_client/src/third_party \
	-I. \
	-Ippapi/native_client/src/shared/ppapi_proxy/trusted \
	-Ippapi

OBJS := \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_callback.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_globals.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_audio_config_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_audio_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_core_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_file_io_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_file_ref_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_file_system_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_find_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_font_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_fullscreen_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_gamepad_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_graphics_2d_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_graphics_3d_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_host_resolver_private_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_image_data_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_input_event_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_instance_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_messaging_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_mouse_cursor_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_mouse_lock_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_net_address_private_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_network_list_private_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_network_monitor_private_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_tcp_server_socket_private_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_tcp_socket_private_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_testing_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_udp_socket_private_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_url_loader_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_url_request_info_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_url_response_info_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_websocket_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppb_zoom_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppp_find.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppp_input_event.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppp_instance.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppp_messaging.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppp_mouse_lock.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppp_printing.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppp_selection.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppp_zoom.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_ppp.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/browser_upcall.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/input_event_data.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/object_serialize.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/ppp_instance_combined.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/utility.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/view_data.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/ppp_rpc_client.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/ppb_rpc_server.o \
	$(obj).target/$(TARGET)/ppapi/native_client/src/shared/ppapi_proxy/upcall_server.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/ppapi/ppapi_c.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-pthread \
	-Wl,-z,noexecstack \
	-m64 \
	-Wl,--icf=none \
	-rdynamic

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-pthread \
	-Wl,-z,noexecstack \
	-m64 \
	-Wl,--icf=none \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	

$(obj).target/ppapi/native_client/src/shared/ppapi_proxy/libnacl_ppapi_browser.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/ppapi/native_client/src/shared/ppapi_proxy/libnacl_ppapi_browser.a: LIBS := $(LIBS)
$(obj).target/ppapi/native_client/src/shared/ppapi_proxy/libnacl_ppapi_browser.a: TOOLSET := $(TOOLSET)
$(obj).target/ppapi/native_client/src/shared/ppapi_proxy/libnacl_ppapi_browser.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/ppapi/native_client/src/shared/ppapi_proxy/libnacl_ppapi_browser.a
# Add target alias
.PHONY: nacl_ppapi_browser
nacl_ppapi_browser: $(obj).target/ppapi/native_client/src/shared/ppapi_proxy/libnacl_ppapi_browser.a

# Add target alias to "all" target.
.PHONY: all
all: nacl_ppapi_browser

