# This file is generated by gyp; do not edit.

export builddir_name ?= /home/padolph/chromium/src/ppapi/native_client/src/shared/ppapi_proxy/out
.PHONY: all
all:
	$(MAKE) -C ../../../../.. nacl_ppapi_browser
