# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := ppapi_example_skeleton
### Rules for final target.
$(obj).target/ppapi/ppapi_example_skeleton.stamp: TOOLSET := $(TOOLSET)
$(obj).target/ppapi/ppapi_example_skeleton.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/ppapi/ppapi_example_skeleton.stamp
# Add target alias
.PHONY: ppapi_example_skeleton
ppapi_example_skeleton: $(obj).target/ppapi/ppapi_example_skeleton.stamp

# Add target alias to "all" target.
.PHONY: all
all: ppapi_example_skeleton

