# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := ppapi_cpp_objects
DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fPIC \
	-fvisibility=hidden \
	-Wextra \
	-pedantic \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := \
	-I.

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fPIC \
	-fvisibility=hidden \
	-Wextra \
	-pedantic \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := \
	-I.

OBJS := \
	$(obj).target/$(TARGET)/ppapi/cpp/array_output.o \
	$(obj).target/$(TARGET)/ppapi/cpp/audio.o \
	$(obj).target/$(TARGET)/ppapi/cpp/audio_config.o \
	$(obj).target/$(TARGET)/ppapi/cpp/core.o \
	$(obj).target/$(TARGET)/ppapi/cpp/file_io.o \
	$(obj).target/$(TARGET)/ppapi/cpp/file_ref.o \
	$(obj).target/$(TARGET)/ppapi/cpp/file_system.o \
	$(obj).target/$(TARGET)/ppapi/cpp/fullscreen.o \
	$(obj).target/$(TARGET)/ppapi/cpp/graphics_2d.o \
	$(obj).target/$(TARGET)/ppapi/cpp/graphics_3d.o \
	$(obj).target/$(TARGET)/ppapi/cpp/graphics_3d_client.o \
	$(obj).target/$(TARGET)/ppapi/cpp/image_data.o \
	$(obj).target/$(TARGET)/ppapi/cpp/input_event.o \
	$(obj).target/$(TARGET)/ppapi/cpp/instance.o \
	$(obj).target/$(TARGET)/ppapi/cpp/instance_handle.o \
	$(obj).target/$(TARGET)/ppapi/cpp/message_loop.o \
	$(obj).target/$(TARGET)/ppapi/cpp/module.o \
	$(obj).target/$(TARGET)/ppapi/cpp/mouse_cursor.o \
	$(obj).target/$(TARGET)/ppapi/cpp/mouse_lock.o \
	$(obj).target/$(TARGET)/ppapi/cpp/rect.o \
	$(obj).target/$(TARGET)/ppapi/cpp/resource.o \
	$(obj).target/$(TARGET)/ppapi/cpp/url_loader.o \
	$(obj).target/$(TARGET)/ppapi/cpp/url_request_info.o \
	$(obj).target/$(TARGET)/ppapi/cpp/url_response_info.o \
	$(obj).target/$(TARGET)/ppapi/cpp/var.o \
	$(obj).target/$(TARGET)/ppapi/cpp/var_array_buffer.o \
	$(obj).target/$(TARGET)/ppapi/cpp/view.o \
	$(obj).target/$(TARGET)/ppapi/cpp/websocket.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/audio_input_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/buffer_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/crypto_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/cursor_control_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/device_ref_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/directory_entry_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/directory_reader_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/file_chooser_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/find_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/font_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/graphics_2d_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/ime_input_event_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/memory_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/printing_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/resource_array_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/scrollbar_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/selection_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/text_input_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/url_util_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/video_capture_client_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/video_capture_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/video_decoder_client_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/video_decoder_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/view_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/widget_client_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/widget_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/zoom_dev.o \
	$(obj).target/$(TARGET)/ppapi/cpp/dev/scriptable_object_deprecated.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/content_decryptor_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/flash.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/flash_clipboard.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/flash_device_id.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/flash_file.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/flash_font_file.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/flash_fullscreen.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/flash_menu.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/flash_message_loop.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/host_resolver_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/instance_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/net_address_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/network_list_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/network_monitor_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/tcp_server_socket_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/tcp_socket_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/udp_socket_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/var_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/private/x509_certificate_private.o \
	$(obj).target/$(TARGET)/ppapi/cpp/trusted/browser_font_trusted.o \
	$(obj).target/$(TARGET)/ppapi/cpp/trusted/file_chooser_trusted.o \
	$(obj).target/$(TARGET)/ppapi/cpp/trusted/file_io_trusted.o \
	$(obj).target/$(TARGET)/ppapi/utility/graphics/paint_aggregator.o \
	$(obj).target/$(TARGET)/ppapi/utility/graphics/paint_manager.o \
	$(obj).target/$(TARGET)/ppapi/utility/private/network_list_observer_private.o \
	$(obj).target/$(TARGET)/ppapi/utility/threading/lock.o \
	$(obj).target/$(TARGET)/ppapi/utility/threading/simple_thread.o \
	$(obj).target/$(TARGET)/ppapi/utility/websocket/websocket_api.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/ppapi/ppapi_c.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-Wl,--icf=none

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-Wl,--icf=none \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	

$(obj).target/ppapi/libppapi_cpp_objects.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/ppapi/libppapi_cpp_objects.a: LIBS := $(LIBS)
$(obj).target/ppapi/libppapi_cpp_objects.a: TOOLSET := $(TOOLSET)
$(obj).target/ppapi/libppapi_cpp_objects.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/ppapi/libppapi_cpp_objects.a
# Add target alias
.PHONY: ppapi_cpp_objects
ppapi_cpp_objects: $(obj).target/ppapi/libppapi_cpp_objects.a

# Add target alias to "all" target.
.PHONY: all
all: ppapi_cpp_objects

