# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := ppapi_shared
DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DGL_GLEXT_PROTOTYPES' \
	'-DSK_BUILD_NO_IMAGE_ENCODE' \
	'-DSK_DEFERRED_CANVAS_USES_GPIPE=1' \
	'-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' \
	'-DGR_AGGRESSIVE_SHADER_OPTS=1' \
	'-DSK_USE_POSIX_THREADS' \
	'-DU_USING_ICU_NAMESPACE=0' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DPPAPI_SHARED_IMPLEMENTATION' \
	'-DPPAPI_THUNK_IMPLEMENTATION' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fPIC \
	-fvisibility=hidden \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/glib-2.0/include \
	-pthread \
	-D_REENTRANT \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/directfb \
	-I/usr/include/libpng12 \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := \
	-Ithird_party/icu/public/common \
	-I. \
	-Ithird_party/khronos \
	-Igpu \
	-Iskia/config \
	-Ithird_party/skia/src/core \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Ithird_party/skia/include/pdf \
	-Ithird_party/skia/include/gpu \
	-Ithird_party/skia/include/gpu/gl \
	-Ithird_party/skia/include/pipe \
	-Ithird_party/skia/include/ports \
	-Ithird_party/skia/include/utils \
	-Iskia/ext \
	-Ithird_party/WebKit/Source/Platform/chromium \
	-Ithird_party/WebKit/Source/Platform/chromium \
	-I$(obj)/gen/webcore_headers \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-Iv8/include

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DGL_GLEXT_PROTOTYPES' \
	'-DSK_BUILD_NO_IMAGE_ENCODE' \
	'-DSK_DEFERRED_CANVAS_USES_GPIPE=1' \
	'-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' \
	'-DGR_AGGRESSIVE_SHADER_OPTS=1' \
	'-DSK_USE_POSIX_THREADS' \
	'-DU_USING_ICU_NAMESPACE=0' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DPPAPI_SHARED_IMPLEMENTATION' \
	'-DPPAPI_THUNK_IMPLEMENTATION' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fPIC \
	-fvisibility=hidden \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/glib-2.0/include \
	-pthread \
	-D_REENTRANT \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/directfb \
	-I/usr/include/libpng12 \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := \
	-Ithird_party/icu/public/common \
	-I. \
	-Ithird_party/khronos \
	-Igpu \
	-Iskia/config \
	-Ithird_party/skia/src/core \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Ithird_party/skia/include/pdf \
	-Ithird_party/skia/include/gpu \
	-Ithird_party/skia/include/gpu/gl \
	-Ithird_party/skia/include/pipe \
	-Ithird_party/skia/include/ports \
	-Ithird_party/skia/include/utils \
	-Iskia/ext \
	-Ithird_party/WebKit/Source/Platform/chromium \
	-Ithird_party/WebKit/Source/Platform/chromium \
	-I$(obj)/gen/webcore_headers \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-Iv8/include

OBJS := \
	$(obj).target/$(TARGET)/ppapi/shared_impl/array_writer.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/callback_tracker.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/file_path.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/file_type_conversion.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/flash_clipboard_format_registry.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/host_resource.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/id_assignment.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/platform_file.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppapi_globals.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppapi_permissions.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppapi_preferences.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppapi_switches.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_audio_config_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_audio_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_crypto_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_device_ref_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_file_io_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_file_ref_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_gamepad_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_graphics_3d_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_image_data_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_input_event_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_instance_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_memory_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_message_loop_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_network_list_private_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_opengles2_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_resource_array_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_url_util_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_var_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_video_decoder_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppb_view_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/ppp_instance_combined.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/proxy_lock.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/resource.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/resource_tracker.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/scoped_pp_resource.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/scoped_pp_var.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/time_conversion.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/tracked_callback.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/url_request_info_data.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/url_response_info_data.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/var.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/var_tracker.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/private/net_address_private_impl.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/private/ppb_char_set_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/private/ppb_host_resolver_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/private/ppb_tcp_server_socket_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/private/ppb_x509_certificate_private_shared.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/private/tcp_socket_private_impl.o \
	$(obj).target/$(TARGET)/ppapi/shared_impl/private/udp_socket_private_impl.o \
	$(obj).target/$(TARGET)/ppapi/thunk/enter.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_audio_config_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_audio_input_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_audio_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_audio_trusted_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_broker_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_browser_font_trusted_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_buffer_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_buffer_trusted_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_char_set_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_console_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_content_decryptor_private_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_cursor_control_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_device_ref_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_directory_reader_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_file_chooser_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_file_io_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_file_io_trusted_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_file_ref_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_file_system_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_find_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_flash_clipboard_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_flash_device_id_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_flash_file_fileref_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_flash_file_modulelocal_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_flash_font_file_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_flash_fullscreen_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_flash_menu_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_flash_message_loop_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_flash_print_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_flash_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_fullscreen_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_gamepad_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_gles_chromium_texture_mapping_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_graphics_2d_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_graphics_3d_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_graphics_3d_trusted_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_host_resolver_private_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_image_data_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_image_data_trusted_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_input_event_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_instance_private_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_instance_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_messaging_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_mouse_cursor_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_mouse_lock_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_network_list_private_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_network_monitor_private_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_printing_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_resource_array_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_scrollbar_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_talk_private_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_tcp_server_socket_private_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_tcp_socket_private_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_text_input_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_udp_socket_private_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_url_loader_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_url_request_info_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_url_response_info_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_url_util_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_video_capture_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_video_decoder_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_view_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_websocket_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_widget_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_x509_certificate_private_thunk.o \
	$(obj).target/$(TARGET)/ppapi/thunk/ppb_zoom_thunk.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/ppapi/ppapi_c.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-L$(builddir) \
	-Wl,--icf=none

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-L$(builddir) \
	-Wl,--icf=none \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	

$(obj).target/ppapi/libppapi_shared.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/ppapi/libppapi_shared.a: LIBS := $(LIBS)
$(obj).target/ppapi/libppapi_shared.a: TOOLSET := $(TOOLSET)
$(obj).target/ppapi/libppapi_shared.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/ppapi/libppapi_shared.a
# Add target alias
.PHONY: ppapi_shared
ppapi_shared: $(obj).target/ppapi/libppapi_shared.a

# Add target alias to "all" target.
.PHONY: all
all: ppapi_shared

